import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/provider/nextauth";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Toaster
          position="top-center"
          pauseWhenPageIsHidden={true}
          theme="dark"
          richColors={true}
        />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
